### ISSUE TITLE
Can you add compatibility information in README.md?

### ISSUE THREAD

**Issue by msmith93** [YutaroHayakawa/ipftrace2#7]
Which operating systems does this tool work on (Centos 7? Centos 8?)? Is there a Linux Kernel version requirement (>=3.10?)?

**Comment by YutaroHayakawa** [comment]
Here we have a spec. Distribution doesn't matter since the ipftrace2 binary is statically linked. Only the kernel version and configuration are the matter.

https://github.com/YutaroHayakawa/ipftrace2#supported-environments

I noticed that I didn't mention about the kernel configuration thanks to you. I'll add it in short.

**Comment by YutaroHayakawa** [comment]
Added kernel config information to README.
